version: "3.8"
services:
  db:
    image: mysql
    container_name: db_hmf
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - dev
  
  phpmyadmin:
    image: phpmyadmin
    container_name: pma_hmf
    restart: always
    depends_on:
    - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev
  
  smtp:
    image: maildev/maildev
    container_name: smtp_hmf
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 8081:80
    restart: always
    networks:
      - dev
      
  apache:
        build: php
        container_name: apache_hmf
        ports:
          - "8888:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev
      
networks:
  dev:

volumes:
  db-data: